version: "3"

services:
  app:
    container_name: app
    build: ./docker/php
    # privileged: true
    expose:
      - 9003
      - 8000
    environment:
      - XDEBUG_SESSION=ListenforXDebug
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-mybbs}
      - DB_USERNAME=${DB_USERNAME:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}

    volumes:
      - ./src/my-bbs:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    # - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  web:
    container_name: web
    build: ./docker/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/my-bbs:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybbs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      # - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    expose:
      - 3306

